from .predefined_resolution_node import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY_MAPPINGS
from .none_constant_node import NODE_CLASS_MAPPINGS as NONE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NONE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**RESOLUTION_MAPPINGS, **NONE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**RESOLUTION_DISPLAY_MAPPINGS, **NONE_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
